version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app/processor/api_requests.db
        target: /app/app/processor/api_requests.db
    env_file:
      - .env
